### ISSUE TITLE
openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'

### ISSUE THREAD

**Issue by yxmnjxzx** [KillianLucas/open-interpreter#251] opened 2023-09-11 00:05 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'interpreter --use-azure.'
2. See error

**Expected behavior**
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 474, in respond
    response = litellm.completion(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 584, in wrapper
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 850, in completion
    raise exception_type(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1960, in exception_type
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1606, in exception_type
    raise original_exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 203, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 474, in respond
    response = litellm.completion(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 584, in wrapper
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 850, in completion
    raise exception_type(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1960, in exception_type
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1606, in exception_type
    raise original_exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 203, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 474, in respond
    response = litellm.completion(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 584, in wrapper
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 850, in completion
    raise exception_type(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1960, in exception_type
    raise e
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1606, in exception_type
    raise original_exception
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 203, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\openai\api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: 'content' is a required property - 'messages.4'
NoneType: None

**Screenshots**

**System (please complete the following information):**
 - OS: win 10
 - Python version 3.10
 - Open Interpreter version (`pip show open-interpreter`):  0.1.2

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 287, in chat
    self.respond()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 811, in respond
    self.respond()
  File "C:\Users\Think\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 509, in respond
    raise Exception("")
Exception

**Comment by jordanbtucker** [comment] 2023-09-11 03:30
Thanks for reporting. Closing as a duplicate of #172

**Closed by jordanbtucker** 2023-09-11 03:30 UTC
Labels: bug
