### ISSUE TITLE
Option to allow fast running (instead of line by line running) of code.

### ISSUE THREAD

**Issue by ZGainsforth** [KillianLucas/open-interpreter#657] opened 2023-10-18 20:55 UTC
### Is your feature request related to a problem? Please describe.

Interpreter will create code efficiently and then start running it.  As it runs, it scrolls through the code line by line to show you where it is during the run.  For code that runs quickly and may have a large number of loops, the time to run can be substantially larger than it should be.  For example, minutes to hours, to loop through code searching a directory structure for specific files, but if I copy paste the code into a python script, it only takes a few seconds.  The latter case doesn't require continual updates to the terminal window.

### Describe the solution you'd like

A command line parameter -r or --run_script would run scripts as scripts instead of within the terminal window.  The code would still print, but then it would spawn a thread and run in the background.  The final output would then be printed.  This would not not show line by line debugger-like progress.

**Comment by koenhandekyn** [comment] 2023-10-23 18:26
i had a similar request. #678 i closed it in favour of this one as this was first.

**Comment by WrathOfGrapes** [comment] 2023-11-07 11:47
+1

This is a huge problem for me as well. Because it can slow a trivial code by a factor of 100 because of console IO bottleneck (or something else related to interpreter mode)

**Comment by MikeBirdTech** [comment] 2024-03-18 19:54
Closing this stale issue. Please create a new issue if the problem is not resolved or explained in the documentation. Thanks!

**Closed by MikeBirdTech** 2024-03-18 19:54 UTC
Labels: enhancement
