### ISSUE TITLE
why

### ISSUE THREAD

**Issue by xyt20021011xy** [KillianLucas/open-interpreter#107] opened 2023-09-07 08:22 UTC
![image](https://github.com/KillianLucas/open-interpreter/assets/99718704/80f6eb33-dd4b-4dc7-ae67-28f896629e8a)

**Comment by Swallow74** [comment] 2023-09-07 09:43
Same issue here (Macbook Air):
 
> create a new conda envinroment named "ciao"
create a new conda envinroment named "ciao"

**Comment by AshwinRamachandran2002** [comment] 2023-09-07 10:35
Are you running the 3B llama model?

**Comment by Swallow74** [comment] 2023-09-07 12:08
> Are you running the 3B llama model?

I tried 7b and 13b, same result

**Comment by TanmayDoesAI** [comment] 2023-09-07 14:17
@xyt20021011xy did you update to the new version? That should fix this problem

**Comment by grexzen** [comment] 2023-09-07 22:16
Look up how to talk to Llama, it has some parameters to use, and not sure they are backed in yet.

**Comment by xyt20021011xy** [comment] 2023-09-08 02:46
> @xyt20021011xy你更新到新版本了吗？这应该可以解决这个问题

![image](https://github.com/KillianLucas/open-interpreter/assets/99718704/6d8a3979-0b1e-4ba5-88ae-5c156f5adfb3)
no

**Comment by TanmayDoesAI** [comment] 2023-09-08 04:11
@xyt20021011xy I believe this problem has been fixed in the update, kindly update using `pip install -U open-interpreter`.

**Comment by jordanbtucker** [comment] 2023-09-08 04:36
I'm closing this issue. Feel free to open it back up if the issue is not resolved.

**Closed by jordanbtucker** 2023-09-08 04:36 UTC
Labels: bug
