### ISSUE TITLE
can not install by pip

### ISSUE THREAD

**Issue by kitianFresh** [KillianLucas/open-interpreter#17] opened 2023-08-31 14:38 UTC
can not install
<img width="1791" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/8846958/8916296a-8af4-4722-9c02-dcbadadf8404">

<img width="1791" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/8846958/e840cace-e2c1-4f36-a380-c68fc2e1857a">

**Comment by KillianLucas** [comment] 2023-08-31 18:07
Hi @kitianFresh! It looks like your Python version is below 3.10, which is the minimum version supported by Open Interpreter.

To be honest, it might work with Python 3.9, I just haven't tested it. If you're up for it, would you be willing to try it? If it works, we could change the supported versions to include 3.9.

If you'd be willing to test it, this code should work:

```shell
# Clone the repository and navigate to the directory
git clone https://github.com/KillianLucas/open-interpreter.git
cd open-interpreter

# Modify the Python version constraint in pyproject.toml
sed -i 's/python = "^3.10"/python = "^3.9"/' pyproject.toml

# Install using Poetry (this will automatically create a virtual environment)
poetry install

# Activate the virtual environment
poetry shell
```

Then run `$: interpreter` and if it works, let me know. If it doesn't, you'll have to [upgrade to Python 3.10](https://blog.enterprisedna.co/how-to-update-python/).

**Comment by KillianLucas** [comment] 2023-09-03 00:08
Hey @kitianFresh, any luck installing via pip?

**Comment by Kamibaloch342** [comment] 2023-09-03 11:50
Hello @KillianLucas 

I was on Python 3.9 and attempted to install it, but it didn't work. I then installed the latest version, 3.11.5, but it still failed. I did not use a virtual environment in this case. 

What do you suggest?
![2023-09-03_16-50_1](https://github.com/KillianLucas/open-interpreter/assets/73388497/57bd2be9-bbcd-4cd3-b0a1-0cee1e635e37)
![2023-09-03_16-50](https://github.com/KillianLucas/open-interpreter/assets/73388497/a7828579-6a02-4007-a7f5-36934e283280)

**Comment by iamsuperzb** [comment] 2023-09-05 02:35
+1

**Comment by Hussseinkizz** [comment] 2023-09-05 11:07
> +1

what do you mean +1 ??

**Comment by Chandrahas-B** [comment] 2023-09-05 13:57
Hey @KillianLucas, I was able to run the interpreter with <b> python 3.9 </b> by modifying the poetry dependencies, is it fine if I raise an issue and PR for the same?

**Comment by Hussseinkizz** [comment] 2023-09-06 11:43
> @Hussseinkizz To use the interpreter, a minimum Python version of 3.10 is required. It appears that you are using python 3.8.10

Ok will update and try again, thanks!

**Comment by NA-Wen** [comment] 2023-09-07 05:07
Hi @kitianFresh 
I met the same problem, just do not change channels when using  ` pip install ` and update python into 3.11 version (maybe 3.10 is also ok) instead of using python 3.9.

**Comment by jordanbtucker** [comment] 2023-09-08 05:29
This is now a duplicate of #170. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:29 UTC
Labels: duplicate
