### ISSUE TITLE
Allow setting custom model directory for local models

### ISSUE THREAD

**Issue by vmajor** [KillianLucas/open-interpreter#691] opened 2023-10-25 09:40 UTC
### Is your feature request related to a problem? Please describe.

There does not appear to be a feature that would allow specifying a local path for local models. Many (all?) users of local models already store their gguf models somewhere. There is no need to re-download them if they already exist locally.

### Describe the solution you'd like

I want to be able to declare a search path for local models as an argument or kwarg, or a simple flag in python.

**Comment by ericrallen** [comment] 2023-10-25 12:40
Closing this as it is a duplicate of #294.

**Closed by ericrallen** 2023-10-25 12:40 UTC
Labels: duplicate

**Comment by vmajor** [comment] 2023-10-26 02:14
I see. It is indeed a duplicate.

For anyone that searches and finds this instead of #294 the simplest solution is to create a symlink and name your model something that corresponds to what is expected, ie. download the smallest model you can and check the file naming syntax.

This also fixes the problem with falcon 180B GGUF where the model is not successfully reassambled from parts. For example I symlinked my 'falcon-180b-chat.Q6_K.gguf' to 'falcon-180b-chat.Q5_0.gguf-split-c' and it works as expected.
