### ISSUE TITLE
Illegal instruction

### ISSUE THREAD

**Issue by apcameron** [KillianLucas/open-interpreter#141] opened 2023-09-07 20:59 UTC
On my Old Desktop I get this error when trying to run it locally
<pre><b>Open Interpreter</b> will use <span style="background-color:#171421"><font color="#2AA1B3"><b>Code Llama</b></font></span> for local execution. Use your arrow keys to
set up the model.                                                               

[<font color="#A2734C">?</font>] Parameter count (smaller is faster, larger is more capable): 7B
 <font color="#12488B">&gt; 7B</font>
   13B
   34B

[<font color="#A2734C">?</font>] Quality (lower is faster, higher is more capable): Low | Size: 3.01 GB, RAM usage: 5.51 GB
 <font color="#12488B">&gt; Low | Size: 3.01 GB, RAM usage: 5.51 GB</font>
   Medium | Size: 4.24 GB, RAM usage: 6.74 GB
   High | Size: 7.16 GB, RAM usage: 9.66 GB

[<font color="#A2734C">?</font>] Use GPU? (Large models might crash on GPU, but will run more quickly) (...: y

Illegal instruction
</pre>

I tried installing it manually with the command below which normally works for other packages but it still fails
CMAKE_ARGS="-DLLAMA_CUBLAS=1 -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_F16C=OFF -DLLAMA_FMA=OFF" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir

dmesg shows the following error
`[31531.797548] traps: interpreter[10882] trap invalid opcode ip:7f215ce3d997 sp:7fffbd2c29f0 error:0 in libllama.so[7f215cdeb000+89000]`

**Comment by apcameron** [comment] 2023-09-07 21:10
Reinstalling from scratch solved the issue

**Comment by KillianLucas** [comment] 2023-09-07 21:45
thanks for opening @apcameron!

> Reinstalling from scratch solved the issue

just open interpreter? or reinstalling `llama-cpp-python`? 

let me know if what you did is in the new [setup guide](https://github.com/KillianLucas/open-interpreter/blob/main/GPU.md), if not we'll add it!

**Comment by apcameron** [comment] 2023-09-07 21:48
Reinstalling with
CMAKE_ARGS="-DLLAMA_CUBLAS=1 -DLLAMA_AVX=OFF -DLLAMA_AVX2=OFF -DLLAMA_F16C=OFF -DLLAMA_FMA=OFF" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir

For some reason it did not work the first time

**Comment by jordanbtucker** [comment] 2023-09-08 05:05
This is now a duplicate of #168. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:05 UTC
Labels: duplicate
