### ISSUE TITLE
Can't seem to type `b` in the interpreter CLI

### ISSUE THREAD

**Issue by StevenBucher98** [KillianLucas/open-interpreter#473] opened 2023-09-21 21:50 UTC
### Describe the bug

For whatever reason, i am unable to type `b` in my CLI, I have confirmed it is not a problem with my keyboard and get a "ding" sound when I try to type b.

### Reproduce

run `interpreter -y`
Try typing `b` and unable to get anything.

### Expected behavior

I can type b

### Open Interpreter version

Version: 0.1.4

### Python version

Python 3.10.12

### Operating System name and version

Mac OS M1 13.5.2 (22G91)

**Comment by ihgalis** [comment] 2023-09-22 09:30
Can you explain more about the context?

I get asked for the OpenAPI Key first which just works for me. Afterwards I can type a question or whatever including the b character. Is it the b within the text you want to type?

**Comment by ericrallen** [comment] 2023-10-12 12:26
Hey there, @StevenBucher98!

This sounds like a local environment issue of some sort.

Also, can you try a fresh `pop install open-interpeter` in a virtual environment and verify it happens with the latest version and a fresh virtual environment?

If the issue is still present , please provide us with some more context, and maybe a screen recording or GIF of this in action?

**Comment by ericrallen** [comment] 2023-10-13 15:05
Going to close this one due to the old version number.

Please reopen this Issue with some more context if you upgrade and the Issue persists.

**Closed by ericrallen** 2023-10-13 15:05 UTC
Labels: bug
