### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#735] opened 2023-11-06 21:49 UTC
### Is your feature request related to a problem? Please describe.

I'd like to know what data is being sent out.

### Describe the solution you'd like

Please write an easy to read privacy policy on what gets sent out, e.g., username, current directory, etc.

### Describe alternatives you've considered

Looking through the source code to find where my data is going

**Comment by ericrallen** [comment] 2023-11-06 23:25
Hey there, @mak448a!

This is essentially a duplicate of your other Issue (#152).

Sorry that no one has gotten to it yet - I promise we do actually care about privacy - but given the volume of Issues and the very small number of contributors, we just haven’t been able to triage this one yet.

I’m going to close this as a duplicate, and we can just keep the discussion in the existing issue.

**Closed by ericrallen** 2023-11-06 23:25 UTC
Labels: duplicate

**Comment by mak448a** [comment] 2023-11-07 01:56
Ok, thank you! @ericallen
