### ISSUE TITLE
Windows installation succeeded, but cannot be used

### ISSUE THREAD

**Issue by snowylchen12** [KillianLucas/open-interpreter#118] opened 2023-09-07 12:22 UTC
![image](https://github.com/KillianLucas/open-interpreter/assets/143569960/c97f1a48-e5d6-4b04-a508-af6243982b8a)
![image](https://github.com/KillianLucas/open-interpreter/assets/143569960/f9d593b5-230b-48be-9b39-533648368b87)

Please help me take a look

**Comment by GroophyLifefor** [comment] 2023-09-07 12:58
@snowylchen12 Try same commands in windows terminal.

**Comment by TanmayDoesAI** [comment] 2023-09-07 14:40
@snowylchen12 can you share the error over text in a code snippet?
so that I could translate it and try to help!

**Comment by hamoudydev** [comment] 2023-09-07 17:31
> @snowylchen12 can you share the error over text in a code snippet? so that I could translate it and try to help!

`interpreter : The term 'interpreter' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1`

**Comment by TonyJiangWJ** [comment] 2023-09-07 17:51
建议使用conda虚拟环境，然后使用cmd而不是PowerShell

**Comment by milgodlewski** [comment] 2023-09-07 19:16
I had the same problem with python version 3.11.0
At first installation was broken, due to missing openai package. I installed it and tried to install open-interpreter with success.
Still - exe was missing.

I was able to resolve it with creation conda env (python 3.11.4) and install open-interpreter again.

**Comment by GroophyLifefor** [comment] 2023-09-07 20:27
> I had the same problem with python version 3.11.0 At first installation was broken, due to missing openai package. I installed it and tried to install open-interpreter. Still - exe was missing.
> 
> I was able to resolve it with creation conda env (python 3.11.4) and install open-interpreter again.

can you give some details like error content or screenshot.

**Comment by jordanbtucker** [comment] 2023-09-07 23:25
Probably this is an issue with your Python/pip `Scripts` directory not being in your `PATH` environment variable.

To find out what that path is, run the following command.

```
python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))'
```

Now [add that directory](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7#file-path-md) to your `PATH` environment variable and restart your terminal.

**Comment by jordanbtucker** [comment] 2023-09-08 05:21
This is now a duplicate of #169. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:21 UTC
Labels: duplicate
