### ISSUE TITLE
API_KEY can not find

### ISSUE THREAD

**Issue by codeacme17** [KillianLucas/open-interpreter#263] opened 2023-09-11 06:29 UTC
### Describe the bug

```bash
  File "C:\Users\vir_k\AppData\Local\pypoetry\Cache\virtualenvs\open-interpreter-5opygHWo-py3.11\Lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

I think this error is caused by this code,
https://github.com/KillianLucas/open-interpreter/blob/7e39d2f595c936209fcf9396cf5d07510e0b5fa2/interpreter/interpreter.py#L380-L383
and
https://github.com/KillianLucas/open-interpreter/blob/7e39d2f595c936209fcf9396cf5d07510e0b5fa2/interpreter/interpreter.py#L442-L444

It seems that storing key variables in `litellm` does not work.
If necessary, I will initiate a PR to resolve this issue

### Reproduce

- interpreter.py
- line 442

### Expected behavior

none

### System (please complete the following information).

- Windows11
- python 3.11.3

**Comment by codeacme17** [comment] 2023-09-11 06:31
I think this is also the reason for issue #258

**Comment by zuchi238** [comment] 2023-09-11 10:25
same here:

File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

Pls suggest a solution (I'm a Newby)

**Comment by ishaan-jaff** [comment] 2023-09-11 14:05
Hello i'm the maintainer of litellm - taking a look at this issue👀

**Comment by Aincvy** [comment] 2023-09-11 14:05
This is an optional solution. In Windows PowerShell, execute the following commands to enter interactive chat mode:

```
$env:OPENAI_API_KEY = "YOUR_API_KEY"
interpreter
```

**Comment by ishaan-jaff** [comment] 2023-09-11 14:49
I can confirm this is because of litellm

quick fix for now:
set `os.environ['OPENAI_API_KEY']`  or `os.environ['AZURE_API_KEY']` 

I'm currently pushing a fix to litellm to fix this problem

**Comment by ishaan-jaff** [comment] 2023-09-11 14:57
i pushed a fix to litellm: https://github.com/BerriAI/litellm/commit/1ef80c9a2a5a188cad7f3192bc183716bfcb040c

**Comment by codeacme17** [comment] 2023-09-11 15:04
Indeed, it seems that there are some problems with the judgment when obtaining variables.

**Comment by ishaan-jaff** [comment] 2023-09-11 17:57
I can confirm this is now fixed on LiteLLM 0.1.590

https://github.com/BerriAI/litellm

**Closed** 2023-09-12 05:27 UTC
Labels: bug

**Comment by zuchi238** [comment] 2023-09-12 06:29
Hi,
(I'm a Newby) but my problem remains
I still see this after I try to use Interpreter

File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

What can I do to fix this. It is not very clear to me

Thanks,

Bart

**Comment by codeacme17** [comment] 2023-09-12 06:37
The fixed PR has been merged. You can fix this problem in the next update.
Currently you can use `$env:OPENAI_API_KEY = "YOUR_API_KEY"` (windows)
Or `export OPENAI_API_KEY ="YOUR_API_KEY"` (mac) to avoid this problem
