### ISSUE TITLE
Can't use GPT 4

### ISSUE THREAD

**Issue by twigs67** [KillianLucas/open-interpreter#538] opened 2023-09-27 19:15 UTC
### Describe the bug

Not sure if this is a bug, but it says the model is set to GPT-4, but it's using GPT-3. I noticed that I could add `interpreter --model gpt-9999` and it will say that I'm using GPT-9999. Does it just default to GPT-3 no matter what? I know my OpenAI API has access to 4. 

### Reproduce

You can ask it "what GPT version am I speaking to" 

### Expected behavior

"You are interacting with a model based on OpenAI's GPT-4 architecture."

### Open Interpreter version

0.1.6

### Python version

3.11

### Operating System name and version

macOS

**Comment by ericrallen** [comment] 2023-09-28 18:56
A few things here:

1. Models aren't self aware and they have knowledge cutoffs (2021-09 is the current for the GPT model available via the API), and GPT-4 was released on 2023-03-14
2. You can make a request directly to the OpenAI API and see similar behavior - 
3. The ChatGPT UI might respond differently, but ChatGPT is its own application, likely running its own model or collection of models - and not just making calls to the same `gpt-4` model we can query via the API
4. GPT-4 is the default model for Open Interpreter, so you can just run `interpreter` and then do a bunch of stuff and check out your [Account Usage Dashboard](https://platform.openai.com/account/usage) - I can confirm that Open Interpreter has been using GPT-4 based on my usage dashboard and the associated costs
5. The `GPT-9999` example does point out a spot where we should probably validate and provide feedback because the `Using Model: X` string is just generated based on whatever you passed in and we should probably create an issue to track that (or modify this issue to describe that behavior)

Here's a screenshot from an [OpenAI chat Obsidian Plugin that I maintain](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant) that also lets you choose between `gpt-4` and `gpt-3.5-turbo` showing the same response from GPT-4. You can see that the model that responded to me was `gpt-4-0613` which the UI grabs directly from the API response.

**Comment by ericrallen** [comment] 2023-10-05 02:13
@twigs67 Anything else on this one or can we close it?

**Comment by ericrallen** [comment] 2023-10-12 12:21
Closing this one for now.

Feel free to reopen if there’s still an Issue.

**Closed by ericrallen** 2023-10-12 12:21 UTC
Labels: bug
