### ISSUE TITLE
Customizable Model Directory

### ISSUE THREAD

**Issue by tb3256** [KillianLucas/open-interpreter#326] opened 2023-09-13 09:27 UTC
### Is your feature request related to a problem? Please describe.

My main drive on C:\ is running out of space so i need to store the models on a different drive

### Describe the solution you'd like

Allow us to set the directory of our models and where they are downloaded with a new --model-dir [directory] command line tag and arg

**Comment by Joackk** [comment] 2023-09-14 05:52
Yes, I also need him. It seems that their default value will be installed in the "appdata\local" directory, and I need to be able to specify his path

**Comment by douglas-hirsh** [comment] 2023-09-14 19:48
If you want to run a model from anywhere you can use the following python file from within a python virtual environment that has the requirements installed.

```python
import interpreter
from llama_cpp import Llama

model_path = "absolute path to your model file"
n_gpu_layers = 40
debug_mode = True
context_window = 16384

llama_2 = Llama(model_path=model_path, n_gpu_layers=n_gpu_layers, verbose=debug_mode, n_ctx=context_window)

interpreter.local = True
interpreter.llama_instance = llama_2
interpreter.chat("Write the code for a fastapi endpoint for todos that supports all CRUD operations. Write all the code in a file called todo_api.py.") # Executes a single command
interpreter.chat() # Starts an interactive chat
```

**Comment by jordanbtucker** [comment] 2023-09-15 05:13
This feature is being considered. For now, you can create a symlink to the directory of your choosing and Open Interpreter will honor that.

**Comment by fynnfluegge** [comment] 2023-09-16 09:10
Would also appreciate this. I already have these models on my system so it rather shouldn't be downloaded twice. Symlink is a good workaround for now. I have an idea how to solve this in a generic way with best user experience. Will raise a PR rather sooner than later 🙌

**Comment by KodeMunkie** [comment] 2023-09-17 23:14
Symlink not really a workaround for Windows machines.

**Comment by ericrallen** [comment] 2023-10-25 12:41
Closing this as it is a duplicate of #294.

**Closed by ericrallen** 2023-10-25 12:41 UTC
Labels: duplicate
