### ISSUE TITLE
Support for Custom llama.cpp models

### ISSUE THREAD

**Issue by razorback16** [KillianLucas/open-interpreter#79] opened 2023-09-06 22:29 UTC
It will be great if the repo provides custom model support with json file description of the model huggingface url and the prompt template. This will help using [Phind-CodeLlama](https://huggingface.co/TheBloke/Phind-CodeLlama-34B-v2-GGUF) or [WizardCoder](https://huggingface.co/WizardLM/WizardCoder-Python-34B-V1.0) model

**Comment by RoversX** [comment] 2023-09-06 22:44
Ye, that's would be so great

**Comment by TanmayDoesAI** [comment] 2023-09-07 07:25
We are working towards implementing open source models, that is one of the priorities. Would be implemented soon.

**Comment by jordanbtucker** [comment] 2023-09-08 15:59
Thanks for the suggestion. I'm going to close this as a duplicate of #183 where it's announced that we're working on this!

**Closed by jordanbtucker** 2023-09-08 15:59 UTC
Labels: duplicate
