### ISSUE TITLE
Response not Displaying code or anything useful

### ISSUE THREAD

**Issue by xavierallem** [KillianLucas/open-interpreter#67] opened 2023-09-06 13:05 UTC
<img width="594" alt="image" src="https://github.com/KillianLucas/open-interpreter/assets/60181637/8d6a9863-d957-44aa-9c78-3634703cf95f">

code-llama 7B Medium 
MacOS M2 8GB Ram

**Comment by Dix01** [comment] 2023-09-07 06:58
> <img alt="image" width="594" src="https://user-images.githubusercontent.com/60181637/266016016-8d6a9863-d957-44aa-9c78-3634703cf95f.png">
> code-llama 7B Medium MacOS M2 8GB Ram

i have the same issue on windows when using code-llama 7B 
RTX 2080 64G Ram

**Comment by jordanbtucker** [comment] 2023-09-08 16:04
This is now a duplicate of #65.

We have fixed this issue in the latest version, please update using `pip install --upgrade open-interpreter`.

**Closed by jordanbtucker** 2023-09-08 16:04 UTC
Labels: duplicate
