### ISSUE TITLE
For some reason it doesn't utilize my GPU, how to deal with this?

### ISSUE THREAD

**Issue by Michael89** [KillianLucas/open-interpreter#114] opened 2023-09-07 10:20 UTC
![Screenshot from 2023-09-07 13-19-28](https://github.com/KillianLucas/open-interpreter/assets/313445/63258afc-5c04-4262-9c12-06dea0ef9cb6)
CPU is high GPU is not utilized at all

**Comment by AshwinRamachandran2002** [comment] 2023-09-07 11:19
You can try this

```
CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir
```

This will reinstall llama_cpp with BLAS backend

**Comment by mpolsky** [comment] 2023-09-07 16:54
> You can try this
> 
> ```
> CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir
> ```
> 
> This will reinstall llama_cpp with BLAS backend

In this case interpreter does not see the package llama-cpp-python at all.
Any suggestions?

**Comment by jordanbtucker** [comment] 2023-09-07 23:30
For Ubuntu and NVIDIA GPUs, you need to have the CUDA Toolkit installed.

Then run
```
CUDA_PATH=/usr/local/cuda FORCE_CMAKE=1 CMAKE_ARGS='-DLLAMA_CUBLAS=on' \
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
```

**Comment by jordanbtucker** [comment] 2023-09-08 04:35
I'm closing this issue. Feel free to open it back up if the issue is not resolved.

**Closed by jordanbtucker** 2023-09-08 04:35 UTC
Labels: duplicate
