### ISSUE TITLE
Issue when executing JavaScript in Windows PowerShell

### ISSUE THREAD

**Issue by andraz** [KillianLucas/open-interpreter#133] opened 2023-09-07 17:32 UTC
At first the error is that it can not execute JavaScript code.

In second try the application crashes and exits back to command line. It also ignores my question, just suggests the same command as in previous reply.

Context window of Code-Llama should be 2048.

```
 interpreter.exe -l

Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 13B
   7B
 > 13B

[?] Quality (lower is faster, higher is more capable): Medium | Size: 8.06 GB, RAM usage: 10.56 GB
   Low | Size: 5.66 GB, RAM usage: 8.16 GB
 > Medium | Size: 8.06 GB, RAM usage: 10.56 GB
   High | Size: 13.83 GB, RAM usage: 16.33 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n):

▌ Model set to Code-Llama
Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> Please reply with just the words "Hello, World!" and nothing else. Do not run code.




  print("Hello, World!")


  Would you like to run this code? (y/n)

  y


  print("Hello, World!")


  Hello, World!


  I will now ask you what you would like me to do next.
Please let me know by replying with a message containing your request.

> in JavaScript print current date formatted as UTC




  console.log(new Date().toUTCString());


  Would you like to run this code? (y/n)

  y


  console.log(new Date().toUTCString());


  Traceback (most recent call last):
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreter.py", line 133, in run
      self.start_process()
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreter.py", line 81, in start_process
      self.proc = subprocess.Popen(start_cmd.split(),
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified



  it seems that there is an issue with the path to the executable. 
Please make sure that the path to the executable is correct and try again. If you are still having issues,
  please let me know and I will do my best to assist you further.

> What executable is needed to execute javascript code?




  console.log(new Date().toUTCString());


  Would you like to run this code? (y/n)

  y


  console.log(new Date().toUTCString());


  Traceback (most recent call last):
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreter.py", line 133, in run
      self.start_process()
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\code_interpreter.py", line 81, in start_process
      self.proc = subprocess.Popen(start_cmd.split(),
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified


llama_tokenize_with_model: too many tokens
Traceback (most recent call last):
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 104, in cli
    cli(self)
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\cli.py", line 46, in cli
    interpreter.chat()
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 256, in chat
    self.respond()
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 679, in respond
    self.respond()
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\interpreter.py", line 469, in respond
    for chunk in response:
  File "C:\Users\andra\AppData\Local\Programs\Python\Python310\lib\site-packages\llama_cpp\llama.py", line 901, in _create_completion
    raise ValueError(
ValueError: Requested tokens (1071) exceed context window of 1048

```

**Comment by TheWhiteWord** [comment] 2023-09-07 21:23
+1 here
https://github.com/KillianLucas/open-interpreter/issues/126#issue-1886202471

**Comment by jordanbtucker** [comment] 2023-09-08 16:41
Thanks for reporting. Closing this as a duplicate of #126

**Closed by jordanbtucker** 2023-09-08 16:41 UTC
Labels: duplicate
