### ISSUE TITLE
"!pip install library" Error

### ISSUE THREAD

**Issue by choies1** [KillianLucas/open-interpreter#402] opened 2023-09-16 13:24 UTC
### Describe the bug

While running the interpreter on the terminal of Windows 11, the interpreter installed a library as follows.

 !pip install PyPDF2

However, it makes the following errors.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\ProgramData\anaconda3\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    !pip install PyPDF2
    ^
SyntaxError: invalid syntax

### Reproduce

I tested the interpreter on the PowerShell of Windows 11.

### Expected behavior

 !pip install PyPDF2

works well without errors

### Screenshots

![image](https://github.com/KillianLucas/open-interpreter/assets/10408785/5eaebae0-5c77-41b1-abfa-eb9f8fca9f86)

### Open Interpreter version

0.1.4

### Python version

3.11.3

### Operating System name and version

Windows 11

**Comment by Czer0xx** [comment] 2023-09-16 13:57
### Install the package manually.
1. Open your terminal
2. Type the command ```pip3 install PyPDF2```
3. Package should be installed

Interpreter has some problem and sometimes prefixes commands with "!" although he is told not to do so.

**Comment by choies1** [comment] 2023-09-16 14:18
Thank you for your reply.

However, the interpreter runs `!pip install PyPDF2` first. It causes some problems.
Is there any method to fix it?

**Comment by TanmayDoesAI** [comment] 2023-09-16 18:52
I am trying to get a fix till then whenever it is installing a library using !pip and you get an error just prompt it with `you could install it, don't use python instead do the install in shell`, This is a temporary fix, till it is fixed.

**Comment by Czer0xx** [comment] 2023-09-16 20:49
Interpreter prefixes commands with '!' because that is how it works in jupyter notebook. The problem is that the language model sometimes doesn't understand when it isn't in jupyter notebook.

**Comment by iwaduarte** [comment] 2023-09-17 07:18
I am also getting this error on windows. I have made it understand that should use windows environment. So it dropped the !.

But still when installing package I am getting 
```

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
    cli(self)
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli.py", line 207, in cli
    interpreter.chat()
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
    self.respond()
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
    code_interpreter.run()
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
    code = wrap_in_try_except(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
    parsed_code = ast.parse(code)
                  ^^^^^^^^^^^^^^^
  File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    pip install beautifulsoup4 requests
        ^^^^^^^
SyntaxError: invalid syntax
```

It looks like that the AST parser have problems with pip install.

**Comment by mak448a** [comment] 2023-09-18 02:27
> I am also getting this error on Windows 11. I have made it understand that should use windows environment. So it dropped the ! (exclamation mark).
> 
> But still when installing packages I am getting
> 
> ```
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 131, in cli
>     cli(self)
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli.py", line 207, in cli
>     interpreter.chat()
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 412, in chat
>     self.respond()
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\interpreter.py", line 924, in respond
>     code_interpreter.run()
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 201, in run
>     code = wrap_in_try_except(code)
>            ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreter.py", line 464, in wrap_in_try_except
>     parsed_code = ast.parse(code)
>                   ^^^^^^^^^^^^^^^
>   File "C:\Users\iwadu\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 50, in parse
>     return compile(source, filename, mode, flags,
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<unknown>", line 2
>     pip install beautifulsoup4 requests
>         ^^^^^^^
> SyntaxError: invalid syntax
> ```
> 
> It looks like that the AST parser have problems with pip install.

The problem is that interpreter is running it in a python console. Related to #163

**Comment by engperini** [comment] 2023-09-20 18:52
> since it's an LLM, we can also use something like "make sure to use pip and not !pip if necessary" in the prompt input

Hi. I have the same problem, running interpreter on venv windows 11.  All command of the Interpreter include "!"  to install packges even when I prompt not to do.

**Comment by nai-kon** [comment] 2023-09-21 07:47
>we can also use something like "make sure to use pip and not !pip if necessary" in the prompt input

It is already written in system prompt, but LLM seems ignore it sometimes.

>Never use (!) when running commands.

https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/system_message.txt#L4

I think the software need to be more error tolerant like below.

* try & catch the exception while command parsing and tell to LLM and retry command.
* remove "!" if the first character of command includes it

**Comment by lborges24** [comment] 2023-09-21 09:42
> > we can also use something like "make sure to use pip and not !pip if necessary" in the prompt input
> 
> It is already written in system prompt, but LLM seems ignore it sometimes.
> 
> > Never use (!) when running commands.
> 
> https://github.com/KillianLucas/open-interpreter/blob/main/interpreter/system_message.txt#L4
> 
> I think the software need to be more error tolerant like below.
> 
> * try & catch the exception while command parsing and tell to LLM and retry command.
> * remove "!" if the first character of command includes it

agree. still I'll make some more prompt tests because it worked on my machine the first time. maybe I was lucky.
- the !pip is because "he" thinks in using "jupiter notebook" but he's not.

**Comment by ericrallen** [comment] 2023-10-12 15:18
Closing this one as I believe this is fixed in more recent versions.

Please feel free to reopen if there’s still an Issue.

**Closed by ericrallen** 2023-10-12 15:18 UTC
Labels: bug
