### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by serhan3535** [KillianLucas/open-interpreter#239] opened 2023-09-10 15:24 UTC
Exception in thread Thread-1 (save_and_display_stream):
Traceback (most recent call last):
  File "G:\Python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "G:\Python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "G:\Softwares\open-interpreter-main\serhan\lib\site-packages\interpreter\code_interpreter.py", line 312, in
save_and_display_stream
    for line in iter(stream.readline, ''):
  File "G:\Python\lib\encodings\cp1254.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 30: character maps to <undefined>

**Comment by jordanbtucker** [comment] 2023-09-11 03:18
Thanks for reporting. Closing as a duplicate of #209

**Closed by jordanbtucker** 2023-09-11 03:18 UTC
Labels: duplicate
