### ISSUE TITLE
Automatically destroy context

### ISSUE THREAD

**Issue by mak448a** [KillianLucas/open-interpreter#161] opened 2023-09-08 03:08 UTC
It would be nice if you could automatically destroy old context in llama 2. The way it is now, if you exceed the context window, it errors with the following:
```
ValueError: Requested tokens (1114) exceed context window of 1048
```

**Comment by jordanbtucker** [comment] 2023-09-08 16:43
Thanks for reporting. Closing this as a duplicate of #126

**Closed by jordanbtucker** 2023-09-08 16:43 UTC
Labels: duplicate
