### ISSUE TITLE
Open Interpreter fails to complete a code request.

### ISSUE THREAD

**Issue by 0000F8** [KillianLucas/open-interpreter#711] opened 2023-10-27 19:52 UTC
### Describe the bug

When trying to output code, the interpreter stops halfway through and tries to run the code. Running interpreter --local -y

### Reproduce

"Build a react native application that supports PDF file viewing."

### Expected behavior

An application that is output locally and run.

### Open Interpreter version

0.1.10

### Python version

3.11.5

### Operating System name and version

MacOS 12.6

### Additional context

None

**Comment by ericrallen** [comment] 2023-10-28 01:10
Hey there, @0000F8!

Can you provide some more context here:

- What model were you using?
- What was it’s output?
- What error message did you receive?

You might also want to consider asking it for a React Native component that can view PDFs and scaffolding the app yourself (or asking it to scaffold the app separately) to save yourself some tokens.

**Comment by Notnaton** [comment] 2023-10-29 16:07
Can replicate:
```
pip install git+https://github.com/KillianLucas/open-interpreter
pip install git+https://github.com/Notnaton/ooba.git@windows --force-reinstall 
```
main.py file:

```
import interpreter

interpreter.model = ""
interpreter.debug_mode = False
interpreter.local  = True
interpreter.max_tokens = 3000
interpreter.chat()
```
Run with: `python main.py`
```
> create a python script and save this script to scripts folder the script should delete only the files inside the Downloads folder that older than 2 months. Please save the deleted file-names in a seperate file.
```
It is unable to finish typing the code. 
![bilde](https://github.com/KillianLucas/open-interpreter/assets/4324290/5c757831-4719-4229-b0a3-022fa03638a6)
No error messages in normal mode

In debug mode:
```
Chunk in `terminal_interface`: {'code': '\n'}
Chunk in coding_llm {'choices': [{'delta': {'content': '\n'}}]}
Chunk in `terminal_interface`: {'code': '\n'}
Chunk in coding_llm {'choices': [{'delta': {'content': '#'}}]}
Chunk in `terminal_interface`: {'code': '#'}

Chunk in `terminal_interface`: {'end_of_code': True}
Running code: {'role': 'assistant', 'message': "Sure, here's a Python script that does what you described:\n", 'language': 'python',    
'code': "import os\nimport shutil\nfrom datetime import datetime, timedelta\n\n# Set the path to the Downloads folder\ndownloads_path = 
'Downloads/'\n\n# Get the current date and subtract 2 months\ntwo_months_ago = datetime.now() - timedelta(days=60)\n\n# Find all files  
in the Downloads folder that are older than two months\nfiles_to_delete = []\nfor filename in os.listdir(downloads_path):\n    filepath 
= os.path.join(downloads_path, filename)\n    if os.path.isfile(filepath) and datetime.fromtimestamp(os.path.getctime(filepath)) <      
two_months_ago:\n        files_to_delete.append(filename)\n\n#"}
Chunk in `terminal_interface`: {'executing': {'code': "import os\nimport shutil\nfrom datetime import datetime, timedelta\n\n# Set the  
path to the Downloads folder\ndownloads_path = 'Downloads/'\n\n# Get the current date and subtract 2 months\ntwo_months_ago =
datetime.now() - timedelta(days=60)\n\n# Find all files in the Downloads folder that are older than two months\nfiles_to_delete =       
[]\nfor filename in os.listdir(downloads_path):\n    filepath = os.path.join(downloads_path, filename)\n    if os.path.isfile(filepath) 
and datetime.fromtimestamp(os.path.getctime(filepath)) < two_months_ago:\n        files_to_delete.append(filename)\n\n#", 'language':   
'python'}}


  import os                                                                                                                             
  import shutil                                                                                                                         
  from datetime import datetime, timedelta                                                                                              
                                                                                                                                        
  # Set the path to the Downloads folder                                                                                                
  downloads_path = 'Downloads/'                                                                                                         
                                                                                                                                        
  # Get the current date and subtract 2 months                                                                                          
  two_months_ago = datetime.now() - timedelta(days=60)                                                                                  
                                                                                                                                        
  # Find all files in the Downloads folder that are older than two months                                                               
  files_to_delete = []                                                                                                                  
  for filename in os.listdir(downloads_path):                                                                                           
      filepath = os.path.join(downloads_path, filename)                                                                                 
      if os.path.isfile(filepath) and datetime.fromtimestamp(os.path.getctime(filepath)) < two_months_ago:                              
          files_to_delete.append(filename)                                                                                              
                                                                                                                                        
  #                                                                                                                                     


  Would you like to run this code? (y/n)

```

**Comment by Notnaton** [comment] 2023-10-29 16:15
There seems to be a max length to the code window:
<details><summary>Details</summary>
<p>

```
Chunk in `terminal_interface`: {'code': 'o'}
Chunk in coding_llm {'choices': [{'delta': {'content': '_'}}]}
Chunk in `terminal_interface`: {'code': '_'}
Chunk in coding_llm {'choices': [{'delta': {'content': 'm'}}]}
Chunk in `terminal_interface`: {'code': 'm'}
Chunk in coding_llm {'choices': [{'delta': {'content': 'o'}}]}
Chunk in `terminal_interface`: {'code': 'o'}


  import os                                                                                                                             
  import shutil                                                                                                                         
  from datetime import datetime, timedelta                                                                                              
                                                                                                                                        
Chunk in coding_llm {'choices': [{'delta': {'content': 'n'}}]}
Chunk in `terminal_interface`: {'code': 'n'}
Chunk in coding_llm {'choices': [{'delta': {'content': 't'}}]}
Chunk in `terminal_interface`: {'code': 't'}
Chunk in coding_llm {'choices': [{'delta': {'content': 'h'}}]}
Chunk in `terminal_interface`: {'code': 'h'}
Chunk in coding_llm {'choices': [{'delta': {'content': 's'}}]}
Chunk in `terminal_interface`: {'code': 's'}

Chunk in `terminal_interface`: {'end_of_code': True}
Running code: {'role': 'assistant', 'message': "Sure, here's the updated Python script that includes checking inside subfolders:\n\n\n",'language': 'python', 'code': "import os\nimport shutil\nfrom datetime import datetime, timedelta\n\n# Set the path to the Downloads    
folder\ndownloads_path = 'Downloads/'\n\n# Get the current date and subtract 2 months\ntwo_months_ago = datetime.now() -
timedelta(days=60)\n\n# Find all files in the Downloads folder that are older than two months, including subfolders\nfiles_to_delete =  
[]\nfor root, dirs, files in os.walk(downloads_path):\n    for filename in files:\n        filepath = os.path.join(root, filename)\n    
if os.path.isfile(filepath) and datetime.fromtimestamp(os.path.getctime(filepath)) < two_months"}
Chunk in `terminal_interface`: {'executing': {'code': "import os\nimport shutil\nfrom datetime import datetime, timedelta\n\n# Set the  
path to the Downloads folder\ndownloads_path = 'Downloads/'\n\n# Get the current date and subtract 2 months\ntwo_months_ago =
datetime.now() - timedelta(days=60)\n\n# Find all files in the Downloads folder that are older than two months, including
subfolders\nfiles_to_delete = []\nfor root, dirs, files in os.walk(downloads_path):\n    for filename in files:\n        filepath =     
os.path.join(root, filename)\n        if os.path.isfile(filepath) and datetime.fromtimestamp(os.path.getctime(filepath)) < two_months", 
'language': 'python'}}


  import os                                                                                                                             
  import shutil                                                                                                                         
  from datetime import datetime, timedelta                                                                                              
                                                                                                                                        
  # Set the path to the Downloads folder                                                                                                
  downloads_path = 'Downloads/'                                                                                                         
                                                                                                                                        
  # Get the current date and subtract 2 months                                                                                          
  two_months_ago = datetime.now() - timedelta(days=60)                                                                                  
                                                                                                                                        
  # Find all files in the Downloads folder that are older than two months, including subfolders                                         
  files_to_delete = []                                                                                                                  
  for root, dirs, files in os.walk(downloads_path):                                                                                     
      for filename in files:                                                                                                            
          filepath = os.path.join(root, filename)                                                                                       
          if os.path.isfile(filepath) and datetime.fromtimestamp(os.path.getctime(filepath)) < two_months                               


  Would you like to run this code? (y/n)
```

</p>
</details>

**Comment by Notnaton** [comment] 2023-10-29 16:50
It seems like it stops generating tokens
It hits this:
![bilde](https://github.com/KillianLucas/open-interpreter/assets/4324290/912a09ff-13bb-43f6-aa81-354a5582c979)
 
<details><summary>respond.py</summary>
<p>

```python
try:

            # Track the type of chunk that the coding LLM is emitting
            chunk_type = None

            for chunk in interpreter._llm(messages_for_llm):

                # Add chunk to the last message
                interpreter.messages[-1] = merge_deltas(interpreter.messages[-1], chunk)

                # This is a coding llm
                # It will yield dict with either a message, language, or code (or language AND code)

                # We also want to track which it's sending to we can send useful flags.
                # (otherwise pretty much everyone needs to implement this)
                if "message" in chunk and chunk_type != "message":
                    chunk_type = "message"
                    yield {"start_of_message": True}
                elif "language" in chunk and chunk_type != "code":
                    chunk_type = "code"
                    yield {"start_of_code": True}
                if "code" in chunk and chunk_type != "code":
                    # (This shouldn't happen though — ^ "language" should be emitted first, but sometimes GPT-3.5 forgets this)
                    # (But I'm pretty sure we handle that? If it forgets we emit Python anyway?)
                    chunk_type = "code"
                    yield {"start_of_code": True}
                elif "message" not in chunk and chunk_type == "message":
                    chunk_type = None
                    yield {"end_of_message": True}

                yield chunk

            # We don't trigger the end_of_message or end_of_code flag if we actually end on either
            if chunk_type == "message":
                yield {"end_of_message": True}
            elif chunk_type == "code":
                yield {"end_of_code": True}
            
        except litellm.exceptions.BudgetExceededError:
``` 

</p>
</details> 
we run out of chunks

**Comment by 0000F8** [comment] 2023-10-31 00:45
> Hey there, @0000F8!
> 
> Can you provide some more context here:
> 
> * What model were you using?
> * What was it’s output?
> * What error message did you receive?
> 
> You might also want to consider asking it for a React Native component that can view PDFs and scaffolding the app yourself (or asking it to scaffold the app separately) to save yourself some tokens.

@ericrallen -- @Notnaton Had the same problem. But also for the sake of completeness on your request, I'm running: Mistral 7B for local execution.

**Comment by altahookah** [comment] 2023-11-04 07:25
Same problem here! running same exact conditions, --local Mistral 7B , just stops generating code and asks for code run

**Comment by Notnaton** [comment] 2023-11-04 09:16
I think we should remove Ooba and use LM Strudio/ GPT4All / Oobabooga through `-ab http://localhost:....`
And add tutorial to set it up for different systems. 
For AMD users GPT4All works wonders, I get 50+ tok/s with their Vulkan shader.

**Comment by ericrallen** [comment] 2023-11-14 22:44
Hey there, folks!

Can anyone confirm if this is still an issue with the latest version of Open Interpreter?

**Comment by Notnaton** [comment] 2023-11-14 22:47
This is no longer an issue on my end. LM Studio works as intended and generates as many tokens as needed.

**Comment by ericrallen** [comment] 2023-11-15 02:01
Thanks, @Notnaton!

I’m going to close this one for now.

**Closed by ericrallen** 2023-11-15 02:01 UTC
Labels: bug, needs verification
