### ISSUE TITLE
Infinite loop identified when code doesn't work

### ISSUE THREAD

**Issue by moshejs** [KillianLucas/open-interpreter#221] opened 2023-09-09 21:04 UTC
**Describe the bug**
When the code fails and hangs up, it repeats the same code over and over again like a madman. The issue is located in the system_message prompt 

**To Reproduce**
When the task gets complicated enough, it spins on itself

**Expected behavior**
Should have some kind of stopper or fallback after several attempts

**System (please complete the following information):**
 - OS: MAX OS X Catalina
 - Python version [e.g. 3.10] 3.11
 - Open Interpreter version (`pip show open-interpreter`): [e.g. 0.1.1] latest

**Additional context**
I submitted a PR :) 

https://github.com/KillianLucas/open-interpreter/pull/220

**Comment by sumihiro** [comment] 2023-09-11 06:38
I have same issue.
I lost $2 because of the infinite loop.

**Comment by bitsnaps** [comment] 2023-09-14 07:04
yes, I had that issue:
```
                                                                                                                   
  It seems there was an error while trying to update the script. The error might be due to the use of single       
  quotes inside the script string. Let's try to fix this by using double quotes for the script string and single   
  quotes inside it.                                                                                                
                                                                                                                   
                                                                                                                   
  It seems there was an error while trying to update the script. The error might be due to the use of single       
  quotes inside the script string. Let's try to fix this by using double quotes for the script string and single   
  quotes inside it.                                                                                                
                                                                                                                   
                                                                                                                   
  It seems there was an error while trying to update the script. The error might be due to the use of single       
  quotes inside the script string. Let's try to fix this by using double quotes for the script string and single   
  quotes inside it.                                                                                                
                                                                                                                   
                                                                                                                   
  It seems there was an error while trying to update the script. The error might be due to the use of single       
  quotes inside the script string. Let's try to fix this by using double quotes for the script string and single   
  quotes inside it. 
```
I think of a simplest approach to implement this using a code check, is to make sure the newly generated code is different from the previous one. In more complex situation I used to prompt the model to run some tests on every iteration (e.g. `pnpm test` or `pytest`...) and see if that makes any improvement.

**Comment by adamxyang** [comment] 2023-09-19 11:47
I'm also seeing CodeLlama-34B repeating itself, shouldn't be an issue with the model but should be something wrong with open-interpreter:
```
> hi
                                                                                                                                                        
  I'll start by asking you some questions about what you want me to do. Please answer them as best you can.                                             
                                                                                                                                                        
  What is the goal of this project? What problem are you trying to solve?                                                                               
                                                                                                                                                        
> I'm writing a tutorial for botorch, I'd like to optimise a toy 4D quadratic function using EI
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> just artificial 4D quadratic toy function
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> EI means expected improvement in botorch
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> pick your own random coefficient
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> pick your own range
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> expected improvement (EI), do you know botorch?
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.                                                                                           
                                                                                                                                                        
> why are you repeating yourself
                                                                                                                                                        
  I understand that you want me to optimize a toy 4D quadratic function using EI. Can you provide more details about the function? What are its         
  coefficients, and what is the range of values for each variable? Additionally, can you tell me what you mean by "EI"? Is it a specific algorithm or   
  a set of algorithms that you want me to use?                                                                                                          
                                                                                                                                                        
  Please let me know if there's anything else I need to know.    
  ```

**Comment by BTCMoBart** [comment] 2023-09-20 14:47
have the same issue, in Windows with Local models.

**Comment by ericsoderquist** [comment] 2023-09-20 18:51
+ 1 issue, windows, local llama 34B, medium. repeats its first response infinitely when continuing to ask questions

**Comment by BTCMoBart** [comment] 2023-09-28 16:34
with the Update Version [v0.1.6] the Issue is gone for me.

**Comment by wyf00747** [comment] 2023-10-07 13:24
i have the same issue with windows11

**Comment by Hetnon** [comment] 2023-10-23 00:54
same issue here.

**Comment by Notnaton** [comment] 2023-11-27 17:58
Should be solved with https://github.com/KillianLucas/open-interpreter/pull/745
Closing, please @ me if it is still an issue

**Closed by Notnaton** 2023-11-27 17:58 UTC
Labels: bug

**Comment by THEBROTHERHD** [comment] 2024-03-27 18:45
@Notnaton i have this Issue right now but in general - it is repeating itself over and over with the first respond generated. I tried various local models using ollama

See this example:

`We were unable to determine the context window of this model. Defaulting to 3000.                                                                   

If your model can handle more, run interpreter --context_window {token limit} --max_tokens {max tokens per response}.                               

Continuing...                                                                                                                                       

                                                                                                                                                    
  Hello Fabian,                                                                                                                                     
                                                                                                                                                    
  I am Open Interpreter, a world-class programmer that can complete any goal by executing code. I have been programmed to execute code on the       
  user's machine and provide the results in a Markdown code block.                                                                                  
                                                                                                                                                    
  To start, let me know what you would like me to do for you. Do you have a specific task or problem that needs solving?                            
                                                                                                                                                    
> please open the pictures folder

                                                                                                                                                    
  Hello Fabian,                                                                                                                                     
                                                                                                                                                    
  I am Open Interpreter, a world-class programmer that can complete any goal by executing code. I have been programmed to execute code on the       
  user's machine and provide the results in a Markdown code block.                                                                                  
                                                                                                                                                    
  To start, let me know what you would like me to do for you. Do you have a specific task or problem that needs solving?                            
                                                                                                                                                    
                                                                                                                                                    
  `markdown` disabled or not supported.                                                                                                             
                                                                                                                                                    
                                                                                                                                                    
  Hello Fabian,                                                                                                                                     
                                                                                                                                                    
  I am Open Interpreter, a world-class programmer that can complete any goal by executing code. I have been programmed to execute code on the       
  user's machine and provide the results in a Markdown code block.                                                                                  
                                                                                                                                                    
  To start, let me know what you would like me to do for you. Do you have a specific task or problem that needs solving?                            
                                                                                                                                                    
> open a new chrome window and search for new Music of Alex Martin
                                                                                                                                                    
  Hello Fabian,                                                                                                                                     
                                                                                                                                                    
  I am Open Interpreter, a world-class programmer that can complete any goal by executing code. I have been programmed to execute code on the       
  user's machine and provide the results in a Markdown code block.                                                                                  
                                                                                                                                                    
  To start, let me know what you would like me to do for you. Do you have a specific task or problem that needs solving?                            
                                                                                                                                                    

                                                                                                                                                    
  computer.browser.search(query) # Google search results will be returned from this function as a string                                            
  computer.files.edit(path_to_file, original_text, replacement_text) # Edit a file                                                                  
  computer.calendar.create_event(title="Meeting", start_date=datetime.datetime.now(), end=datetime.datetime.now() + datetime.timedelta(hours=1),    
  notes="Note", location="") # Creates a calendar event                                                                                             
  computer.calendar.get_events(start_date=datetime.date.today(), end_date=None) # Get events between dates. If end_date is None, only gets events   
  for start_date                                                                                                                                    
  computer.calendar.delete_event(event_title="Meeting", start_date=datetime.datetime) # Delete a specific event with a matching title and start     
  date, you may need to get use get_events() to find the specific event object first                                                                
  computer.contacts.get_phone_number("John Doe")                                                                                                    
  computer.contacts.get_email_address("John Doe")                                                                                                   
  computer.mail.send("john@                                                                                                                         
                              `

**Comment by THEBROTHERHD** [comment] 2024-03-27 18:47
▌ OS Control enabled                                                                                                                              

> 
write hi to puma on discord
                                                                                                                                                    
                                                                                                                                                    
  To summarize text:                                                                                                                                
                                                                                                                                                    
   1 First, understand what the user wants you to do.                                                                                               
   2 Start by executingcomputer.browser.search(query) with a suitable search query. For example, if the user wants you to summarize "The Great      
     Gatsby", the query could be "summary of The Great Gatsby".                                                                                     
   3 Use thecomputer.display.view() command to see what's on the screen after executing step 2. Verify that the search results are visible and      
     note down any relevant information you find.                                                                                                   
   4 If necessary, use other commands likecomputer.keyboard.hotkey(" ", "command")`,computer.mouse.click(x=500, y=500) to navigate through the      
     webpage and extract more information.                                                                                                          
   5 Continue doing this in small steps, verifying your progress at every step withcomputer.display.view()`.                                        
   6 Finally, when you have gathered all the necessary information, use a suitable natural language processing or summarization algorithm (you can  
     find several on GitHub) to create a summary of the text.                                                                                       
   7 If needed, paste this summary into the appropriate text field or application that the user is using.                                           
   8 Executecomputer.display.view() once again to verify that the summary has been successfully posted.                                             
                                                                                                                                                    
  To summarize text:                                                                                                                                
                                                                                                                                                    
   1 First, understand what the user wants you to do.                                                                                               
   2 Start by executingcomputer.browser.search(query) with a suitable search query. For example, if the user wants you to summarize "The Great      
     Gatsby", the query could be "summary of The Great Gatsby".                                                                                     
   3 Use thecomputer.display.view()                                                                                                                 
                                                                                                                                                    
> 

... and this is constantly printed out over and over again - i waited 5 minutes and then exited

**Comment by Notnaton** [comment] 2024-03-27 19:04
Known issue. Working on a fix @THEBROTHERHD
