### ISSUE TITLE
Output disappears when I use the open-interpreter in Jupyter Notebook

### ISSUE THREAD

**Issue by choies1** [KillianLucas/open-interpreter#411] opened 2023-09-17 02:43 UTC
### Is your feature request related to a problem? Please describe.

When I use the open-interpreter in Terminal, the output does not disappear.
But when I use it in Jupyter Notebook, the output is visible for a while and then disappears. 
Is there any way to make the output not disappear?

### Describe the solution you'd like

I'd like to be able to see all of my output in Jupyter Notebook without it disappearing, just like when I use open-interpreter in Terminal.

**Comment by DecaiJin** [comment] 2023-09-19 04:19
I found the same question!!!

**Comment by hoshins** [comment] 2023-09-19 09:19
I faced same situation. I updated python version from 3.10 to 3.11 but there is nothing changed

**Comment by ericrallen** [comment] 2023-11-14 22:51
Hey there, folks!

I'm going to close this one as a duplicate of #52 

Let's keep any Jupyter discussion there.

Thanks!

**Closed by ericrallen** 2023-11-14 22:51 UTC
Labels: duplicate, enhancement
