### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by pyoneerC** [KillianLucas/open-interpreter#153] opened 2023-09-07 23:59 UTC
windows powershell 

PS C:\Users\Usuario> pip install open-interpreter
Requirement already satisfied: open-interpreter in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.1.1)
Requirement already satisfied: appdirs<2.0.0,>=1.4.4 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (1.4.4)
Requirement already satisfied: astor<0.9.0,>=0.8.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (0.8.1)
Requirement already satisfied: git-python<2.0.0,>=1.0.3 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (1.0.3)
Requirement already satisfied: inquirer<4.0.0,>=3.1.3 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (3.1.3)
Requirement already satisfied: openai<0.28.0,>=0.27.8 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (0.27.10)
Requirement already satisfied: pyreadline3<4.0.0,>=3.4.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (3.4.1)
Requirement already satisfied: rich<14.0.0,>=13.4.2 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (13.5.2)
Requirement already satisfied: six<2.0.0,>=1.16.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (1.16.0)
Requirement already satisfied: tiktoken<0.5.0,>=0.4.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (0.4.0)
Requirement already satisfied: tokentrim<0.2.0,>=0.1.9 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (0.1.10)
Requirement already satisfied: wget<4.0,>=3.2 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from open-interpreter) (3.2)
Requirement already satisfied: gitpython in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from git-python<2.0.0,>=1.0.3->open-interpreter) (3.1.35)
Requirement already satisfied: blessed>=1.19.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.20.0)
Requirement already satisfied: python-editor>=1.0.4 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (1.0.4)
Requirement already satisfied: readchar>=3.0.6 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from inquirer<4.0.0,>=3.1.3->open-interpreter) (4.0.5)
Requirement already satisfied: requests>=2.20 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openai<0.28.0,>=0.27.8->open-interpreter) (2.31.0)
Requirement already satisfied: tqdm in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openai<0.28.0,>=0.27.8->open-interpreter) (4.66.1)
Requirement already satisfied: aiohttp in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from openai<0.28.0,>=0.27.8->open-interpreter) (3.8.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from rich<14.0.0,>=13.4.2->open-interpreter) (2.16.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tiktoken<0.5.0,>=0.4.0->open-interpreter) (2023.8.8)
Requirement already satisfied: wcwidth>=0.1.4 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter) (0.2.6)
Requirement already satisfied: jinxed>=1.1.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter) (1.2.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from markdown-it-py>=2.2.0->rich<14.0.0,>=13.4.2->open-interpreter) (0.1.2)
Requirement already satisfied: setuptools>=41.0 in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\lib\site-packages (from readchar>=3.0.6->inquirer<4.0.0,>=3.1.3->open-interpreter) (65.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.20->openai<0.28.0,>=0.27.8->open-interpreter) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.20->openai<0.28.0,>=0.27.8->open-interpreter) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.20->openai<0.28.0,>=0.27.8->open-interpreter) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests>=2.20->openai<0.28.0,>=0.27.8->open-interpreter) (2023.7.22)
Requirement already satisfied: attrs>=17.3.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from aiohttp->openai<0.28.0,>=0.27.8->open-interpreter) (1.3.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (4.0.10)
Requirement already satisfied: colorama in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from tqdm->openai<0.28.0,>=0.27.8->open-interpreter) (0.4.6)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from gitdb<5,>=4.0.1->gitpython->git-python<2.0.0,>=1.0.3->open-interpreter) (5.0.0)
Requirement already satisfied: ansicon in c:\users\usuario\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jinxed>=1.1.0->blessed>=1.19.0->inquirer<4.0.0,>=3.1.3->open-interpreter) (1.89.0)
PS C:\Users\Usuario> interpreter
interpreter : The term 'interpreter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ interpreter
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (interpreter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Usuario> interpreter -y
interpreter : The term 'interpreter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ interpreter -y
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (interpreter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by scrachatron** [comment] 2023-09-08 01:23
missing from your path settings. 

python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))' 

duplicate of 118
https://github.com/KillianLucas/open-interpreter/issues/118

**Comment by pyoneerC** [comment] 2023-09-08 01:29
C:\Users>python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))'
  File "<string>", line 1
    'import
    ^
SyntaxError: unterminated string literal (detected at line 1)

**Comment by jordanbtucker** [comment] 2023-09-08 05:19
This is now a duplicate of #169. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:19 UTC
Labels: duplicate
