### ISSUE TITLE
llama-7b

### ISSUE THREAD

**Issue by Raclez** [KillianLucas/open-interpreter#308] opened 2023-09-12 23:33 UTC
### Describe the bug

I'm using the llama model to answer the first question but everything after that is the answer to the first question why is that
![image](https://github.com/KillianLucas/open-interpreter/assets/82217572/d684f2f1-b50c-41ce-a866-8d96e1dbd582)

### Reproduce

interpreter --local

### Expected behavior

and Can not use  gpt3.5

### Open Interpreter version

0.1.1

### Python version

3.9.0

### Operating System name and version

macos13

**Comment by mak448a** [comment] 2023-09-13 02:09
Having the same issue on Fedora Linux, Python3.11.

**Comment by TanmayDoesAI** [comment] 2023-09-13 14:13
Thank you for reporting the bug, kindly share what comes in the response when you use `%debug`, so that we could understand the problem better!

**Comment by mak448a** [comment] 2023-09-17 02:14
I can't reproduce it anymore, but I think the problem is still there.

**Comment by mak448a** [comment] 2023-09-18 03:02
````[
    {'role': 'user', 'content': 'List the files in this directory'},
    {
        'content': "\n\nLet's start with listing the files in the current directory.\n```shell\nls -l\n```",
        'function_call': {'parsed_arguments': {'code': 'ls -l', 'language': 'shell'}},
        'role': 'assistant'
    },
    {
        'role': 'function',
        'name': 'run_code',
        'content': 'total 192\n-rw-r--r--. 1 mak448a mak448a   3615 Sep 17 21:37 CONTRIBUTING.md\ndrwxr-xr-x. 1 mak448a mak448a     48 Sep 17 21:37 docs\ndrwxr-xr-x. 1 mak448a 
mak448a    276 Sep 17 21:58 interpreter\n-rw-r--r--. 1 mak448a mak448a   1070 Sep 17 21:37 LICENSE\n-rw-r--r--. 1 mak448a mak448a 114745 Sep 17 21:37 poetry.lock\n-rw-r--r--. 1 
mak448a mak448a    974 Sep 17 21:37 pyproject.toml\n-rw-r--r--. 1 mak448a mak448a  20648 Sep 17 21:37 README_IN.md\n-rw-r--r--. 1 mak448a mak448a  11440 Sep 17 21:37 
README_JA.md\n-rw-r--r--. 1 mak448a mak448a   9621 Sep 17 21:37 README.md\n-rw-r--r--. 1 mak448a mak448a   8407 Sep 17 21:37 README_ZH.md\n-rw-r--r--. 1 mak448a mak448a   2438 Sep 
17 21:37 SECURITY.md\ndrwxr-xr-x. 1 mak448a mak448a     38 Sep 17 21:37 tests'
    },
    {
        'content': ' it appears that there are several files and directories in this directory.\n\nTo list only the files in this directory, we can use the `-f` option with `ls`. 
This will show only the files and not the directories.\n```shell\nls -l -f\n```',
        'function_call': {'parsed_arguments': {'code': 'ls -l -f', 'language': 'shell'}},
        'role': 'assistant'
    },
    {
        'role': 'function',
        'name': 'run_code',
        'content': 
'.\n..\n.git\n.env.sample\n.github\n.gitignore\n.vscode\nCONTRIBUTING.md\nLICENSE\nREADME.md\nREADME_IN.md\nREADME_JA.md\nREADME_ZH.md\nSECURITY.md\ndocs\ninterpreter\npoetry.lock\
npyproject.toml\ntests\n.idea'
    },
    {
        'content': ' it appears that there are several files and directories in this directory. To list only the files in this directory, we can use the `-f` option with `ls`. This
will show only the files and not the directories.\n```shell\nls -l -f\n```',
        'function_call': {'parsed_arguments': {'code': 'ls -l -f', 'language': 'shell'}},
        'role': 'assistant'
    },
    {
        'role': 'function',
        'name': 'run_code',
        'content': 
'.\n..\n.git\n.env.sample\n.github\n.gitignore\n.vscode\nCONTRIBUTING.md\nLICENSE\nREADME.md\nREADME_IN.md\nREADME_JA.md\nREADME_ZH.md\nSECURITY.md\ndocs\ninterpreter\npoetry.lock\
npyproject.toml\ntests\n.idea'
    },
    {}
]
```

**Comment by mak448a** [comment] 2023-09-18 03:05
Please note that I have modified the prompt slightly to get it to run bash properly because of #163. The modified part was the following: "\n\nTo run code, write a fenced code block (i.e ```python, R or ```shell) in markdown. Whenever you are using bash, use ```shell. When you close it with ```, it will be run. You'll then be given its output."

**Comment by ericrallen** [comment] 2023-10-21 17:18
Local models, especially heavily quantized ones can be prone to repetition without careful prompting and often need the temperature, rope frequency (especially for Llama-derived models), and other settings tweaked to suit the model and your use of it.

Going to close this one as it’s not about an older version of Open Interpreter.

Feel free to reopen if you update to the latest and still experience the same issue.

**Closed by ericrallen** 2023-10-21 17:18 UTC
Labels: bug
