### ISSUE TITLE
Python path cant be found

### ISSUE THREAD

**Issue by kllgjc** [KillianLucas/open-interpreter#633] opened 2023-10-12 15:19 UTC
### Describe the bug

> check to see that hello world command works in python. do nothing else

  print('Hello, World!')

  Traceback (most recent call last):
    File
  "C:\Users\xxx\AppData\Local\anaconda3\lib\site-packages\interpreter\code_interpreters\subprocess_code_interpreter
  .py", line 65, in run
      self.start_process()
    File
  "C:\Users\xxx\AppData\Local\anaconda3\lib\site-packages\interpreter\code_interpreters\subprocess_code_interpreter
  .py", line 43, in start_process
      self.process = subprocess.Popen(self.start_cmd.split(),
    File "C:\Users\xxx\AppData\Local\anaconda3\lib\subprocess.py", line 971, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\xxx\AppData\Local\anaconda3\lib\subprocess.py", line 1440, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified

however, when it invokes it directly, it works 

> invoke the path directly C:\Users\xxx\AppData\Local\anaconda3\python.exe

  !C:\Users\xxx\AppData\Local\anaconda3\python.exe -c 'print("Hello, World!")'

  Microsoft Windows [Version 10.0.19045.3324]
  (c) Microsoft Corporation. All rights reserved.
  (base) C:\>C:\Users\xxx\AppData\Local\anaconda3\python.exe -c 'print("Hello, World!")'

  The python.exe file was successfully invoked and the 'Hello, World!' printed correctly. This indicates that Python
  is properly installed and reachable on your system. We are ready to proceed with any Python related tasks.

### Reproduce

x

### Expected behavior

y

### Screenshots

z

### Open Interpreter version

0.1.9

### Python version

3.10.9

### Operating System name and version

windows 10

**Comment by jmottishaw** [comment] 2023-10-13 21:50
Same issue here.

**Comment by geerties99** [comment] 2023-10-14 13:14
same issue for me

**Comment by Kwalladee** [comment] 2023-10-16 22:19
I am experiencing the same issue as well for all queries.

**Comment by sacra2kx** [comment] 2023-10-18 09:44
same problem here

**Comment by pmiddlet72** [comment] 2023-10-18 20:54
Possible duplicate of Issue #635 ?  If so, a fix which will probably be released in a future update has been posted here: https://github.com/KillianLucas/open-interpreter/issues/635#issuecomment-1763522797  .   I've run into this issue and this appears to work.

**Comment by pmiddlet72** [comment] 2023-10-19 23:30
Ah one other thing - the Python interpreter should be in the path of your environment vars. That's one other error I've noted. I don't think that setting this was listed in the docs as a requirement upon install (it should). Hopefully that should avoid having to target the exact path to your python executable.

**Comment by mayuri2307** [comment] 2023-10-23 11:23
> Ah one other thing - the Python interpreter should be in the path of your environment vars. That's one other error I've noted. I don't think that setting this was listed in the docs as a requirement upon install (it should). Hopefully that should avoid having to target the exact path to your python executable.

I agree, if python is not configured in the environment variables, then this issue comes up. I think you can add that as a requirement.

**Comment by Kwalladee** [comment] 2023-10-23 21:05
> > Ah one other thing - the Python interpreter should be in the path of your environment vars. That's one other error I've noted. I don't think that setting this was listed in the docs as a requirement upon install (it should). Hopefully that should avoid having to target the exact path to your python executable.
> 
> I agree, if python is not configured in the environment variables, then this issue comes up. I think you can add that as a requirement.

For me this issue arises while working on a company machine where I do not have access to change the environment variables, and where I had to install Python from the Microsoft store. XD

**Comment by ericrallen** [comment] 2023-11-03 17:31
Going to close this one as stale for now.

Feel free to reopen it if there is more to discuss, but this seems like a PATH issue in the local environment.

**Closed by ericrallen** 2023-11-03 17:31 UTC
Labels: bug, needs verification
