### ISSUE TITLE
Problem installating `llama-cpp-python`

### ISSUE THREAD

**Issue by JanWerder** [KillianLucas/open-interpreter#59] opened 2023-09-06 06:41 UTC
I'm using Windows 11 and have trouble installing Open Interpreter.

```
Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 34B
   7B
   16B
 > 34B

[?] Quality (lower is faster, higher is more capable): Medium | Size: 20.22 GB, RAM usage: 22.72 GB
   Low | Size: 14.21 GB, RAM usage: 16.71 GB
 > Medium | Size: 20.22 GB, RAM usage: 22.72 GB
   High | Size: 35.79 GB, RAM usage: 38.29 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): Y

[?] This instance of `Code-Llama` was not found. Would you like to download it? (Y/n): Y


curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL

 Finished downloading `Code-Llama`.

[?] `Code-Llama` interface package not found. Install `llama-cpp-python`? (Y/n): Y

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Lib\site-packages\pip\__main__.py", line 22, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Python311\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Python311\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Python311\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Python311\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Python311\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Python311\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 37, in <module>
    from pip._vendor.tenacity import retry, stop_after_delay, wait_fixed
  File "C:\Python311\Lib\site-packages\pip\_vendor\tenacity\__init__.py", line 548, in <module>
    from pip._vendor.tenacity._asyncio import AsyncRetrying  # noqa:E402,I100
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\pip\_vendor\tenacity\_asyncio.py", line 21, in <module>
    from asyncio import sleep
  File "C:\Python311\Lib\asyncio\__init__.py", line 42, in <module>
    from .windows_events import *
  File "C:\Python311\Lib\asyncio\windows_events.py", line 8, in <module>
    import _overlapped
OSError: [WinError 10106] Der angeforderte Dienstanbieter konnte nicht geladen oder initialisiert werden
Error during installation with cuBLAS: Command '['C:\\Python311\\python.exe', '-m', 'pip', 'install',
'llama-cpp-python']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\interpreter\llama_2.py", line 94, in get_llama_2_instance
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 90, in cli
    cli(self)
  File "C:\Python311\Lib\site-packages\interpreter\cli.py", line 59, in cli
    interpreter.chat()
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 148, in chat
    self.llama_instance = get_llama_2_instance()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\interpreter\llama_2.py", line 151, in get_llama_2_instance
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
```

**Comment by Pawandeep-prog** [comment] 2023-09-06 06:58
try installing it manually 
```pip install --upgrade llama-cpp-python```
it should solve

**Comment by JanWerder** [comment] 2023-09-06 07:44
Thanks, that worked, but it seems like there is still an issue with downloading the models on windows.

```
Open Interpreter will use Code Llama for local execution. Use your arrow keys to set up the model.

[?] Parameter count (smaller is faster, larger is more capable): 34B
   7B
   16B
 > 34B

[?] Quality (lower is faster, higher is more capable): Medium | Size: 20.22 GB, RAM usage: 22.72 GB
   Low | Size: 14.21 GB, RAM usage: 16.71 GB
 > Medium | Size: 20.22 GB, RAM usage: 22.72 GB
   High | Size: 35.79 GB, RAM usage: 38.29 GB

[?] Use GPU? (Large models might crash on GPU, but will run more quickly) (Y/n): Y

[?] This instance of `Code-Llama` was not found. Would you like to download it? (Y/n):

curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL
curl: (3) URL using bad/illegal format or missing URL

 Finished downloading `Code-Llama`.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 90, in cli
    cli(self)
  File "C:\Python311\Lib\site-packages\interpreter\cli.py", line 59, in cli
    interpreter.chat()
  File "C:\Python311\Lib\site-packages\interpreter\interpreter.py", line 148, in chat
    self.llama_instance = get_llama_2_instance()
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\interpreter\llama_2.py", line 176, in get_llama_2_instance
    llama_2 = Llama(model_path=model_path, n_gpu_layers=n_gpu_layers, verbose=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\llama_cpp\llama.py", line 312, in __init__
    raise ValueError(f"Model path does not exist: {model_path}")
ValueError: Model path does not exist: C:\Users\janwe\AppData\Local\Open Interpreter\Open Interpreter\models\codellama-34b.Q4_K_M.gguf
```

**Comment by Pawandeep-prog** [comment] 2023-09-06 07:50
you can manually download the models and place them at 
```C:\Users\janwe\AppData\Local\Open Interpreter\Open Interpreter\models\```

I found these links from the code from where it downloads the models:
```
models = {
        '7B': {
            'Low': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-7B-GGUF/resolve/main/codellama-7b.Q2_K.gguf', 'Size': '3.01 GB', 'RAM': '5.51 GB'},
            'Medium': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-7B-GGUF/resolve/main/codellama-7b.Q4_K_M.gguf', 'Size': '4.24 GB', 'RAM': '6.74 GB'},
            'High': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-7B-GGUF/resolve/main/codellama-7b.Q8_0.gguf', 'Size': '7.16 GB', 'RAM': '9.66 GB'}
        },
        '16B': {
            'Low': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-13B-GGUF/resolve/main/codellama-13b.Q2_K.gguf', 'Size': '5.66 GB', 'RAM': '8.16 GB'},
            'Medium': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-13B-GGUF/resolve/main/codellama-13b.Q4_K_M.gguf', 'Size': '8.06 GB', 'RAM': '10.56 GB'},
            'High': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-13B-GGUF/resolve/main/codellama-13b.Q8_0.gguf', 'Size': '13.83 GB', 'RAM': '16.33 GB'}
        },
        '34B': {
            'Low': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/resolve/main/codellama-34b.Q2_K.gguf', 'Size': '14.21 GB', 'RAM': '16.71 GB'},
            'Medium': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/resolve/main/codellama-34b.Q4_K_M.gguf', 'Size': '20.22 GB', 'RAM': '22.72 GB'},
            'High': {'URL': 'https://huggingface.co/TheBloke/CodeLlama-34B-GGUF/resolve/main/codellama-34b.Q8_0.gguf', 'Size': '35.79 GB', 'RAM': '38.29 GB'}
        }
    }
```

**Comment by Maxdesigna7x** [comment] 2023-09-06 12:45
where put the downloaded model? ROOT/models/ don't work for my.

**Comment by Thevivek10** [comment] 2023-09-06 13:10
try installing it manually
pip install --upgrade llama-cpp-python
it should solve

**Comment by jordanbtucker** [comment] 2023-09-08 05:09
I'm closing this issue. Feel free to open it back up if the issue is not resolved.

**Closed by jordanbtucker** 2023-09-08 05:09 UTC
Labels: duplicate
