### ISSUE TITLE
How to change the download path of the llama model.

### ISSUE THREAD

**Issue by c469591** [KillianLucas/open-interpreter#159] opened 2023-09-08 02:40 UTC
Hello, may I ask if it is possible to change the download path for the llama model? I am using Windows and by default, it downloads to C:. However, my C drive does not have enough space. Therefore, I would like to download it to another drive. Is there any way to do this? Thank you.

**Comment by jordanbtucker** [comment] 2023-09-08 03:17
There is no built-in option, but you can set up a symbolic link or junction to accomplish this.

First, move the `models` directory to the place you want it on the other drive. By default it's located at `%LOCALAPPDATA%\Open Interpreter\Open Interpreter\models`.

For this example, the new location will be `D:\Open Interpreter\models`.

```
# Command Prompt
mklink /j "%LOCALAPPDATA%\Open Interpreter\Open Interpreter\models" "D:\Open Interpreter\models"

# PowerShell
New-Item -ItemType Junction `
-Name "$env:LOCALAPPDATA\Open Interpreter\Open Interpreter\models" -Target 'D:\Open Interpreter\models'
```

**Comment by jordanbtucker** [comment] 2023-09-08 04:20
I'm closing this issue. Feel free to open it back up if the issue is not resolved.

**Closed by jordanbtucker** 2023-09-08 04:20 UTC
Labels: question

**Comment by cemre-2187** [comment] 2024-09-01 18:24
I encountered an issue with the large folder size of Llama 3.1. The suggested solution didn't work for me because I use separate disks. However, I found a workaround that might help others facing the same issue. Llama uses the `llama` CLI for downloads.

To find the path of the Llama CLI, you can type:

```bash
which llama
```

You should see something like this:

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from llama_toolchain.cli.llama import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

From this, we can understand that the CLI uses the `llama_toolchain.cli` module. To change the output directory, navigate to your Python libraries and find the `llama_toolchain` library. Then go to `/cli/download.py`.

In this file, you'll find lines that specify output file paths like this:

```python
output_dir = Path(model_local_dir(model.descriptor()))
```

You can change these lines to specify your new path:

```python
output_dir = Path("/your-new-path")
```

This should resolve the issue and allow Llama to download without any problems to your new path.

**Comment by iazulkarnain** [comment] 2024-10-14 05:19
Put the following lines into your .bashrc. It works for me.

```
# default value: LLAMA_STACK_CONFIG_DIR=~/.llama
export LLAMA_STACK_CONFIG_DIR=<your_new_path>
```

In case it doesn't work, you may check the source codes of llama_stack libraries as new versions may implement different env variable names. I found my solution after assessing the following scripts:

```
<your_env_dir>/lib/python3.10/site-packages/llama_stack/cli/download.py
<your_env_dir>/lib/python3.10/site-packages/llama_stack/distribution/utils/model_utils.py
<your_env_dir>/lib/python3.10/site-packages/llama_stack/distribution/utils/config_dirs.py
```

Hope this helps.

**Comment by shamrockmuffin** [comment] 2024-10-14 20:26
Thanks for the insights and saved headaches

**Comment by m4th3w561** [comment] 2024-12-14 09:55
> There is no built-in option, but you can set up a symbolic link or junction to accomplish this.
> 
> First, move the `models` directory to the place you want it on the other drive. By default it's located at `%LOCALAPPDATA%\Open Interpreter\Open Interpreter\models`.
> 
> For this example, the new location will be `D:\Open Interpreter\models`.
> 
> ```
> # Command Prompt
> mklink /j "%LOCALAPPDATA%\Open Interpreter\Open Interpreter\models" "D:\Open Interpreter\models"
> 
> # PowerShell
> New-Item -ItemType Junction `
> -Name "$env:LOCALAPPDATA\Open Interpreter\Open Interpreter\models" -Target 'D:\Open Interpreter\models'
> ```

I was getting the same problem when I was trying to download llama 3.3
But this did the trick for me! Thank you so much!

atm, I think the directories are set to `.llama` so I had to adjust some portion of the snippet. 
And it seems like llama downloads within my Windows profile.
 
`mklink /D "C:\Users\<Your_Username>\.llama" "D:\<Directory_Name>"` 

If it's looking for the `checkpoints` directory just add it to wherever you were linking the output directory, in my case I added `checkpoints` directory in my "D:\<Directory_Name>"
