### ISSUE TITLE
Does it use Wizardcoder or vanilla codellama as a default for --local?

### ISSUE THREAD

**Issue by Gyro0o** [KillianLucas/open-interpreter#156] opened 2023-09-08 01:27 UTC
Does it use Wizardcoder or vanilla codellama as a default?
And can we change the base model?

**Comment by jordanbtucker** [comment] 2023-09-08 03:38
Currently it uses GGUF versions of vanilla CodeLlama. You can see the links in [llama_2.py](https://github.com/KillianLucas/open-interpreter/blob/07f1cda27fc9e5518b63822e1d6175761ea1edf0/interpreter/llama_2.py#L17).

**Comment by jordanbtucker** [comment] 2023-09-08 04:21
Currently the models are hard coded, but support for other models may be added in later.

I'm closing this issue. Feel free to open it back up if the issue is not resolved.

**Closed by jordanbtucker** 2023-09-08 04:21 UTC
