### ISSUE TITLE
interpreter -y command outputs bash: interpreter: command not found

### ISSUE THREAD

**Issue by meezlung** [KillianLucas/open-interpreter#51] opened 2023-09-05 19:03 UTC
I have already verified the installation using "pip install open-interpreter" and there seems to be no errors. However, once I run interpreter command, the terminal shows nothing. 

I am kinda new to this. Any chance I'm doing something wrong?

**Comment by valerie-makes** [comment] 2023-09-05 19:51
This StackOverflow question may help you:

https://stackoverflow.com/questions/35898734/pip-installs-packages-successfully-but-executables-not-found-from-command-line

**Comment by dusk-chancellor** [comment] 2023-09-06 15:39
I have also installed it successfully but when I write "interpreter" on my cmd it says that there is no any command named like that. I'm total newbie, do I do something wrong?

**Comment by jordanbtucker** [comment] 2023-09-08 05:13
This is now a duplicate of #169. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:13 UTC
Labels: duplicate
