### ISSUE TITLE
OSError: [WinError 10106] Error during installation with cuBLAS: Command '['C:\\ProgramData\\Anaconda3\\envs\\py3-11\\python.exe', '-m', 'pip', 'install', 'llama-cpp-python']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ncepu-blgy** [KillianLucas/open-interpreter#91] opened 2023-09-07 04:18 UTC
My operating system environment：
windows 11, python3.11.5,nvdia  cuBLAS, v11.7

when type: interpreter -y, the erroras follows：
OSError: [WinError 10106] 无法加载或初始化请求的服务提供程序。
Error during installation with cuBLAS: Command '['C:\\ProgramData\\Anaconda3\\envs\\py3-11\\python.exe', '-m', 'pip',
'install', 'llama-cpp-python']' returned non-zero exit status 1.

▌ Failed to install Code-LLama.

We have likely not built the proper Code-Llama support for your system.

( Running language models locally is a difficult task! If you have insight into the best way to implement this across
platforms/architectures, please join the Open Interpreter community Discord and consider contributing the project's
development. )

Please press enter to switch to GPT-4 (recommended).
![image](https://github.com/KillianLucas/open-interpreter/assets/20950018/d58792d4-5603-433e-aa22-c401f90697c7)
![2023-09-07_115835](https://github.com/KillianLucas/open-interpreter/assets/20950018/9fa31a14-9b63-4f9c-9d1f-2cae54a83416)

What is the cause of the above error and how can I fix it?

**Comment by ncepu-blgy** [comment] 2023-09-07 04:20
And, the llama-cpp-python has been installed standalone.

![image](https://github.com/KillianLucas/open-interpreter/assets/20950018/76b6bdab-8d41-4107-b7c2-2f321744dc16)

**Comment by sourasis** [comment] 2023-09-07 19:09
Same error for me on my windows 10 , python 3.10.11, cuda v11.3

**Comment by euphoriaman** [comment] 2023-09-07 22:11
Same for me....

**Comment by jordanbtucker** [comment] 2023-09-07 23:02
See [Code-Llama on Windows](https://github.com/jordanbtucker/open-interpreter/blob/windows/WINDOWS.md).

Then if you have an NVIDIA GPU, see [Local Language Models with GPU Support](https://github.com/KillianLucas/open-interpreter/blob/main/GPU.md).

**Comment by jordanbtucker** [comment] 2023-09-08 05:06
This is now a duplicate of #167. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:06 UTC
Labels: duplicate
