### ISSUE TITLE
Could not find a version that satisfies the requirement open-interpreter

### ISSUE THREAD

**Issue by LCehoennardo** [KillianLucas/open-interpreter#38] opened 2023-09-04 11:48 UTC
I got this error after run `pip install open-interpreter`

```
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
```

How to fix this, help

**Comment by KillianLucas** [comment] 2023-09-04 20:52
Hi @LCehoennardo! Let me know what `python --version` you're using — hopefully it's just an outdated Python install (right now we just support Python 3.10 and up). If not we can dig deeper. Thanks!

**Comment by LCehoennardo** [comment] 2023-09-05 12:42
> Hi @LCehoennardo! Let me know what `python --version` you're using — hopefully it's just an unsupported Python version (right now we just support Python 3.10 and up). If not we can dig deeper. Thanks!

Thank you. My python version is 3.9, I will upgrade it and retry.

**Comment by ykosinets** [comment] 2023-09-06 11:26
Same for 2.7.18

**Comment by andotorg** [comment] 2023-09-07 01:54
Have you solved it? I've encountered this problem too.

**Comment by andotorg** [comment] 2023-09-07 01:57
settings 
sudo vi ~/.bash_profile 
alias python=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3
alias pip=/Library/Frameworks/Python.framework/Versions/3.10/bin/pip3
source ~/.bash_profile 
successful !

**Comment by andotorg** [comment] 2023-09-07 01:58
> settings sudo vi ~/.bash_profile alias python=/Library/Frameworks/Python.framework/Versions/3.10/bin/python3 alias pip=/Library/Frameworks/Python.framework/Versions/3.10/bin/pip3 source ~/.bash_profile successful !

my pc is macos 10.15.7

**Comment by ToxsickOX** [comment] 2023-09-07 19:06
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter
Iam using Ubuntu python 3.11.5

**Comment by joshsaintjacque** [comment] 2023-09-08 02:25
I have Python 3.11 and ran into this issue. I got around it by running:
```
pip install open-interpreter --ignore-requires-python
```

**Comment by jordanbtucker** [comment] 2023-09-08 05:36
This is now a duplicate of #170. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:36 UTC

**Comment by Raclez** [comment] 2023-09-08 06:42
pip install open-interpreter --ignore-requires-python

**Comment by marioBaltiSolar** [comment] 2023-09-15 11:31
I just run this command pip install open-interpreter --ignore-requires-python and I could install it but when I run this command `interpreter` I get 
_'interpreter' is not recognized as an internal or external command,
operable program or batch file._

**Comment by sunnyfarfetch** [comment] 2023-09-20 23:09
Please open command prompt as administrator and then type:
python 
to start python in cmd. Then start putting this:

import interpreter
interpreter.chat("Plot AAPL and META's normalized stock prices") # Executes a single command
interpreter.chat() # Starts an interactive chat

It will ask you for open api key.

It worked for me.

Happy coding.

**Comment by Akshat-Gurnani** [comment] 2024-02-03 09:15
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.10,<4.0; 0.0.2 Requires-Python >=3.10,<4.0; 0.0.21 Requires-Python >=3.10,<4.0; 0.0.22 Requires-Python >=3.10,<4.0; 0.0.221 Requires-Python >=3.10,<4.0; 0.0.222 Requires-Python >=3.10,<4.0; 0.0.223 Requires-Python >=3.10,<4.0; 0.0.224 Requires-Python >=3.10,<4.0; 0.0.225 Requires-Python >=3.10,<4.0; 0.0.226 Requires-Python >=3.10,<4.0; 0.0.227 Requires-Python >=3.10,<4.0; 0.0.228 Requires-Python >=3.10,<4.0; 0.0.229 Requires-Python >=3.10,<4.0; 0.0.230 Requires-Python >=3.10,<4.0; 0.0.231 Requires-Python >=3.10,<4.0; 0.0.232 Requires-Python >=3.10,<4.0; 0.0.233 Requires-Python >=3.10,<4.0; 0.0.234 Requires-Python >=3.10,<4.0; 0.0.235 Requires-Python >=3.10,<4.0; 0.0.236 Requires-Python >=3.10,<4.0; 0.0.237 Requires-Python >=3.10,<4.0; 0.0.238 Requires-Python >=3.10,<4.0; 0.0.239 Requires-Python >=3.10,<4.0; 0.0.240 Requires-Python >=3.10,<4.0; 0.0.241 Requires-Python >=3.10,<4.0; 0.0.242 Requires-Python >=3.10,<4.0; 0.0.243 Requires-Python >=3.10,<4.0; 0.0.244 Requires-Python >=3.10,<4.0; 0.0.245 Requires-Python >=3.10,<4.0; 0.0.246 Requires-Python >=3.10,<4.0; 0.0.247 Requires-Python >=3.10,<4.0; 0.0.248 Requires-Python >=3.10,<4.0; 0.0.249 Requires-Python >=3.10,<4.0; 0.0.250 Requires-Python >=3.10,<4.0; 0.0.251 Requires-Python >=3.10,<4.0; 0.0.252 Requires-Python >=3.10,<4.0; 0.0.253 Requires-Python >=3.10,<4.0; 0.0.254 Requires-Python >=3.10,<4.0; 0.0.255 Requires-Python >=3.10,<4.0; 0.0.256 Requires-Python >=3.10,<4.0; 0.0.257 Requires-Python >=3.10,<4.0; 0.0.258 Requires-Python >=3.10,<4.0; 0.0.259 Requires-Python >=3.10,<4.0; 0.0.260 Requires-Python >=3.10,<4.0; 0.0.261 Requires-Python >=3.10,<4.0; 0.0.262 Requires-Python >=3.10,<4.0; 0.0.263 Requires-Python >=3.10,<4.0; 0.0.264 Requires-Python >=3.10,<4.0; 0.0.265 Requires-Python >=3.10,<4.0; 0.0.266 Requires-Python >=3.10,<4.0; 0.0.267 Requires-Python >=3.10,<4.0; 0.0.268 Requires-Python >=3.10,<4.0; 0.0.269 Requires-Python >=3.10,<4.0; 0.0.270 Requires-Python >=3.10,<4.0; 0.0.271 Requires-Python >=3.10,<4.0; 0.0.272 Requires-Python >=3.10,<4.0; 0.0.273 Requires-Python >=3.10,<4.0; 0.0.274 Requires-Python >=3.10,<4.0; 0.0.275 Requires-Python >=3.10,<4.0; 0.0.276 Requires-Python >=3.10,<4.0; 0.0.277 Requires-Python >=3.10,<4.0; 0.0.278 Requires-Python >=3.10,<4.0; 0.0.279 Requires-Python >=3.10,<4.0; 0.0.280 Requires-Python >=3.10,<4.0; 0.0.281 Requires-Python >=3.10,<4.0; 0.0.282 Requires-Python >=3.10,<4.0; 0.0.283 Requires-Python >=3.10,<4.0; 0.0.284 Requires-Python >=3.10,<4.0; 0.0.285 Requires-Python >=3.10,<4.0; 0.0.286 Requires-Python >=3.10,<4.0; 0.0.287 Requires-Python >=3.10,<4.0; 0.0.288 Requires-Python >=3.10,<4.0; 0.0.289 Requires-Python >=3.10,<4.0; 0.0.290 Requires-Python >=3.10,<4.0; 0.0.291 Requires-Python >=3.10,<4.0; 0.0.292 Requires-Python >=3.10,<4.0; 0.0.293 Requires-Python >=3.10,<4.0; 0.0.294 Requires-Python >=3.10,<4.0; 0.0.295 Requires-Python >=3.10,<4.0; 0.0.296 Requires-Python >=3.10,<4.0; 0.0.297 Requires-Python >=3.10,<4.0; 0.1.0 Requires-Python >=3.10,<4.0; 0.1.1 Requires-Python >=3.10,<4.0; 0.1.10 Requires-Python >=3.10,<4.0; 0.1.11 Requires-Python >=3.10,<3.12; 0.1.12 Requires-Python >=3.10,<3.12; 0.1.13 Requires-Python >=3.10,<3.12; 0.1.14 Requires-Python >=3.10,<3.12; 0.1.15 Requires-Python >=3.10,<3.12; 0.1.16 Requires-Python >=3.10,<3.12; 0.1.17 Requires-Python >=3.10,<3.12; 0.1.18 Requires-Python >=3.9,<4.0; 0.1.2 Requires-Python >=3.10,<4.0; 0.1.3 Requires-Python >=3.10,<4.0; 0.1.4 Requires-Python >=3.10,<4.0; 0.1.5 Requires-Python >=3.10,<4.0; 0.1.6 Requires-Python >=3.10,<4.0; 0.1.7 Requires-Python >=3.10,<4.0; 0.1.8 Requires-Python >=3.10,<4.0; 0.1.9 Requires-Python >=3.10,<4.0; 0.2.0 Requires-Python >=3.9,<4.0
ERROR: Could not find a version that satisfies the requirement open-interpreter (from versions: none)
ERROR: No matching distribution found for open-interpreter

Hi, receiving this error kindly provide assistance
