### ISSUE TITLE
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it

### ISSUE THREAD

**Issue by risingwen** [KillianLucas/open-interpreter#216] opened 2023-09-09 15:45 UTC
PS D:\> interpreter

▌ Model set to GPT-4

Tip: To run locally, use interpreter --local

Open Interpreter will require approval before running code. Use interpreter -y to bypass this.

Press CTRL-C to exit.

> hi
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\interpreter\interpreter.py", line 104, in cli
    cli(self)
  File "C:\Program Files\Python310\lib\site-packages\interpreter\cli.py", line 46, in cli
    interpreter.chat()
  File "C:\Program Files\Python310\lib\site-packages\interpreter\interpreter.py", line 256, in chat
    self.respond()
  File "C:\Program Files\Python310\lib\site-packages\interpreter\interpreter.py", line 388, in respond
    response = openai.ChatCompletion.create(
  File "C:\Program Files\Python310\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "C:\Program Files\Python310\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "C:\Program Files\Python310\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Program Files\Python310\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by jordanbtucker** [comment] 2023-09-09 16:16
Thanks for reporting this. I'm closing it as a duplicate of #121. Please review and continue discussion there if you still run into problems.

**Closed by jordanbtucker** 2023-09-09 16:16 UTC
Labels: bug
