### ISSUE TITLE
mac installation works but can't find interpreter cmd

### ISSUE THREAD

**Issue by itsPreto** [KillianLucas/open-interpreter#122] opened 2023-09-07 14:04 UTC
> `pip freeze`:

<img width="248" alt="Screenshot 2023-09-07 at 9 58 58 AM" src="https://github.com/KillianLucas/open-interpreter/assets/45348368/f3e35028-0eb0-461d-abed-97730af871e5">

> `interpreter --local`:

<img width="638" alt="Screenshot 2023-09-07 at 9 59 31 AM" src="https://github.com/KillianLucas/open-interpreter/assets/45348368/f8d97eff-c609-44d3-9184-8e978debec0a">

**Comment by itsPreto** [comment] 2023-09-07 16:16
[SOLVED]

First run:
<img width="743" alt="Screenshot 2023-09-07 at 12 15 12 PM" src="https://github.com/KillianLucas/open-interpreter/assets/45348368/9919cb30-46c7-464a-a698-b649bf850249">

Then add the python 'Location' to your PATH

```bash 
export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
```

Or, you can create a syslink:

```bash 
sudo ln -s /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/interpreter /usr/local/bin/interpreter
```

**Comment by maxpetrusenko** [comment] 2023-09-07 18:33
After I run the command above I see:

zsh: permission denied: interpreter

**Comment by itsPreto** [comment] 2023-09-07 21:27
@maxpetrusenko yeah I forgot to update this again but even though it recognizes the cmd it still gave me this permission denied so I decided to just start a conda environment for it and it worked right away.

**Comment by jordanbtucker** [comment] 2023-09-07 23:04
Probably this is an issue with your Python/pip `Scripts` directory not being in your `PATH` environment variable.

To find out what that path is, run the following command.

```
python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))'
```

Now [add that directory](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7#file-path-md) to your `PATH` environment variable and restart your terminal.

**Comment by jordanbtucker** [comment] 2023-09-08 05:20
This is now a duplicate of #169. If you still need help, please leave a comment on that issue.

**Closed by jordanbtucker** 2023-09-08 05:20 UTC
Labels: duplicate

**Comment by Raclez** [comment] 2023-09-08 20:23
> `Scripts`这可能是您的 Python/pip目录不在环境变量中的问题`PATH`。
> 
> 要找出该路径是什么，请运行以下命令。
> 
> ```
> python -c 'import os,sysconfig;print(sysconfig.get_path("scripts"))'
> ```
> 
> 现在[将该目录添加](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7#file-path-md)到环境变量中`PATH`并重新启动终端。

I did it your way, and it still didn't work

**Comment by Raclez** [comment] 2023-09-08 20:24
> 运行上面的命令后我看到：
> 
> zsh：权限被拒绝：解释器

me too
