### ISSUE TITLE
Support for more large language models

### ISSUE THREAD

**Issue by ruanrongman** [KillianLucas/open-interpreter#210] opened 2023-09-09 08:31 UTC
I really appreciate your creativity, but I have looked at the project code. I think If you want to support more large language models or future extensions, excessive coupling will make it difficult. Are you planning to increase the abstraction of the code， just like Langchain.

**Comment by yuan-thomas** [comment] 2023-09-09 10:24
Second this. Or just reference to Langchain by accepting an initialized langchain.schema.language_model.BaseLanguageModel?

**Comment by ruanrongman** [comment] 2023-09-09 12:34
> Second this. Or just reference to Langchain by accepting an initialized langchain.schema.language_model.BaseLanguageModel?

I think so.

**Comment by jordanbtucker** [comment] 2023-09-09 16:19
Thanks for suggesting this. I'm closing it as a duplicate of #183.

**Closed by jordanbtucker** 2023-09-09 16:19 UTC
Labels: enhancement
